### ISSUE TITLE
coverlet.collector is missing dependencies

### ISSUE THREAD

**Issue by jdanielbioc** [tonerdo/coverlet#672]
Unlisted dependency on old version of FileSystemGlobbing is causing problems starting a project in built in 3.1.

Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.FileSystemGlobbing, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Microsoft.Extensions.FileSystemGlobbing, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.ChangeTokenInfo..ctor
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.ChangeTokenInfo..ctor(CancellationTokenSource tokenSource, CancellationChangeToken changeToken)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.GetOrAddFilePathChangeToken(String filePath)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.GetOrAddChangeToken(String pattern)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider..ctor(JsonConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Bioclinica.ClinFeed.OrchestrationService.Program.Main(String[] args) in C:\agent-intg\_work\51\s\OrchestrationService\Program.cs:line 14

**Comment by MarcoRossignoli** [comment]
Hi  @jdanielbioc the issue is not clear to me, this exception seem unrelated to Coverlet, I mean coverlet instruments users asm before run test, can you attach the command line you used to run test?

**Comment by jdanielbioc** [comment]
Marco,

Sorry if I was unclear coverlet was in the test project as you suggested, but after publishing everything the main project was unable to run due to the old version of FileSystemGlobbing that coverlet had loaded into the test project.

Regards,
Jeremy

**Comment by MarcoRossignoli** [comment]
Can you attach you command line?
When you say publishing you mean `dotnet publish` and after `dotnet vstest lib.dll`?

**Comment by jdanielbioc** [comment]
We ran “dotnet clean” followed by “dotnet publish -o app/publish” at the level of the solution file. When the test project references coverlet.collector app/publish has the wrong version of the file globbing dll. We are not looking to fix that, just the incorrect display of dependencies on nuget.org which made it harder to track down this as the cause.

JEREMY DANIEL
SENIOR PRODUCT DEVELOPER
Bioclinica
211 Carnegie Center Drive
Princeton, New Jersey 08540 USA
Based Remotely in Boston, MA, USA
email  jeremy.daniel@bioclinica.com
bioclinica.com
________________________________

**Comment by MarcoRossignoli** [comment]
Yup when publishing all files are moved to target directory(also coverlet nuget package files) so globbing dll is overwrite. I'm wondering why you don't run test without publishing, only using `dotnet test --collect:"XPlat Code Coverage"` from root(where sln file is placed) or from csproj folder, in this way Coverlet files are not copied to output and globbing dll shouldn't be overwrite.

**Comment by MarcoRossignoli** [comment]
> We are not looking to fix that, just the incorrect display of dependencies on nuget.org which made it harder to track down this as the cause.

You're right, unfortunatly coverlet is packed as `build` assets https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets because it runs before and after tests(imports props and target files) and is not consumed as a lib so nuget ui doesn't show any dependencies because all files are "embedded" and also because it's not a consumed "dependency" for the project is using it.
Btw if possible I advice to use `dotnet test ...` and not run `dotnet publish/dotnet vstest ...dll` so libs shouldn't be moved to target folder.

![image](https://user-images.githubusercontent.com/7894084/71785843-d634ac00-3004-11ea-8204-c812a330303d.png)

For now I'll tag as-designed, I'll do some search to understand if make sense/is possible document in some way from nuget.org site perspective.

Feel free to close if solved.
