### ISSUE TITLE
MissingMethodException when collecting with VSTest

### ISSUE THREAD

**Issue by chvrl** [tonerdo/coverlet#751]
I'm seeing if I can switch to coverlet.collector from coverlet.msbuild, but I'm running into an issue with one of my test projects. It's testing a library that has a reference to a nuget package (specifically Microsoft.ApplicationInsights.AspNetCore) that is interfering with coverlet.core's dependency on Microsoft.Extensions.DependencyInjection.

I was able to reproduce the issue with a stripped-down project [uploaded here](https://github.com/chvrl/test-example).

Workarounds:
- Adding an explicit package reference to Microsoft.Extensions.DependencyInjection to the test (or tested) project.
- Downgrading to coverlet.collector 1.0.1 (since 1.1.0 has the same issue in this situation).

Here's the console output when run on the linked project.
```
> dotnet test --collect:"XPlat Code Coverage"
UnitTest1.cs(11,29): warning CS0219: The variable 'telemetryClient' is assigned but its value is never used [C:\[...]\TestProject\TestProject.csproj]
Test run for C:\[...]\TestProject\bin\Debug\netcoreapp3.1\TestProject.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Data collector 'XPlat code coverage' message: [coverlet]System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.ServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.
   at Coverlet.Core.DependencyInjection.InitDefaultServices()
   at Coverlet.Core.DependencyInjection.<>c.<.cctor>b__5_0() in D:\git\coverletToRelease\src\coverlet.core\DependencyInjection.cs:line 11
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Coverlet.Core.DependencyInjection.get_Current() in D:\git\coverletToRelease\src\coverlet.core\DependencyInjection.cs:line 17
   at Coverlet.Collector.DataCollection.CoverageWrapper.CreateCoverage(CoverletSettings settings, ILogger coverletLogger) in D:\git\coverletToRelease\src\coverlet.collector\DataCollection\CoverageWrapper.cs:line 21
   at Coverlet.Collector.DataCollection.CoverageManager..ctor(CoverletSettings settings, IReporter[] reporters, ILogger logger, ICoverageWrapper coverageWrapper) in D:\git\coverletToRelease\src\coverlet.collector\DataCollection\CoverageManager.cs:line 52
   at Coverlet.Collector.DataCollection.CoverageManager..ctor(CoverletSettings settings, TestPlatformEqtTrace eqtTrace, TestPlatformLogger logger, ICoverageWrapper coverageWrapper) in D:\git\coverletToRelease\src\coverlet.collector\DataCollection\CoverageManager.cs:line 43
   at Coverlet.Collector.DataCollection.CoverletCoverageCollector.OnSessionStart(Object sender, SessionStartEventArgs sessionStartEventArgs) in D:\git\coverletToRelease\src\coverlet.collector\DataCollection\CoverletCoverageCollector.cs:line 124.

Test Run Successful.
Total tests: 1
     Passed: 1
 Total time: 1.4826 Seconds
```

**Comment by MarcoRossignoli** [comment]
I think your workaround is the only applicable at the moment...coverlet uses dependency injection libs https://github.com/tonerdo/coverlet/blob/master/Directory.Build.targets#L6-L8 https://github.com/tonerdo/coverlet/blob/master/src/coverlet.core/DependencyInjection.cs

But `Microsoft.ApplicationInsights.AspNetCore` reference a very old one 

![image](https://user-images.githubusercontent.com/7894084/75820667-10b88c00-5d9d-11ea-9240-66d3e626fc5b.png)
